---
name: idr0119-gross-cellresponse/screenA
version: 1

defaults:
  # Should the column be processed when creating bulk-annotations (yes/no)
  include: no
  # Columns type of the bulk-annotations column
  type: string

  # If non-empty a string used to separate multiple fields in a column
  # White space will be stripped
  split: ","
  # Should this column be included in the clients (yes/no)
  includeclient: yes
  # Should this column be visible in the clients, if no the column should be
  # hidden in the client but will still be indexed by the searcher (yes/no)
  visible: yes
  # Should empty values be omitted from the client display
  omitempty: yes

columns:
  - name: Tissue Type 1
    clientname: Tissue Type 1
    include: true

  - name: Tissue Type 2
    clientname: Tissue Type 2
    include: true

  - name: Control Type
    clientname: Control Type
    include: true


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/cell_line
      columns:
        - name: Characteristics [Cell Line]
          clientname: Cell Line
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/compound
      columns:
        - name: Compound 1 Name
          clientname: Compound Name
          include: yes
        - name: Compound 1 PubChem CID
          clientname: Compound Name URL
          clientvalue: >
            https://pubchem.ncbi.nlm.nih.gov/compound/{{ value|urlencode }}
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/compound
      columns:
        - name: Compound 2 Name
          clientname: Compound Name
          include: yes
        - name: Compound 2 PubChem CID
          clientname: Compound Name URL
          clientvalue: >
            https://pubchem.ncbi.nlm.nih.gov/compound/{{ value|urlencode }}
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/compound/supplementary
      columns:
        - name: Compound 1 Name
          clientname: Compound Name
          include: yes
        - name: Compound 1 PubChem CID
          clientname: PubChem CID
          include: true
        - name: Compound 1 PubChem URL
          clientname: PubChem URL
          include: true
        - name: Compound 1 Concentration (microMolar)
          clientname: Concentration (microMolar)
          include: true
        - name: Compound 1 InChIKey
          clientname: InChIKey
          include: true
        - name: Compound 1 SMILES
          clientname: SMILES
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/compound/supplementary
      columns:
        - name: Compound 2 Name
          clientname: Compound Name
          include: yes
        - name: Compound 2 PubChem CID
          clientname: PubChem CID
          include: true
        - name: Compound 2 PubChem URL
          clientname: PubChem URL
          include: true
        - name: Compound 2 Concentration (nanoMolar)
          clientname: Concentration (nanoMolar)
          include: true
        - name: Compound 2 InChIKey
          clientname: InChIKey
          include: true
        - name: Compound 2 SMILES
          clientname: SMILES
          include: true


advanced:
  well_to_images: yes
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/cell_line
      keys:
        - Cell Line
    - namespace: openmicroscopy.org/mapr/compound
      keys:
        - Compound Name
        - Compound Name URL
